"""Store links for more info on breeds."""

BREED_URLS = {'Akita': 'https://www.akc.org/dog-breeds/akita/',
              'American Bulldog': 'http://www.ababulldogs.com/',
              'American Staffordshire Terrier': 'https://www.akc.org/dog-breeds/american-staffordshire-terrier/',
              'Basset Hound': 'https://www.akc.org/dog-breeds/basset-hound/',
              'Beagle': 'https://www.akc.org/dog-breeds/beagle/',
              'Belgian Shepherd / Malinois': 'https://www.akc.org/dog-breeds/belgian-malinois/',
              'Black Labrador Retriever': 'https://www.akc.org/dog-breeds/labrador-retriever/',
              'Bloodhound': 'https://www.akc.org/dog-breeds/bloodhound/',
              'Boxer': 'https://www.akc.org/dog-breeds/boxer/',
              'Bullmastiff': 'https://www.akc.org/dog-breeds/bullmastiff/',
              'Cane Corso': 'https://www.akc.org/dog-breeds/cane-corso',
              'Cavalier King Charles Spaniel': 'https://www.akc.org/dog-breeds/cavalier-king-charles-spaniel',
              'Chihuahua': 'https://www.akc.org/dog-breeds/chihuahua/',
              'Chocolate Labrador Retriever': 'https://www.akc.org/dog-breeds/labrador-retriever/',
              'Chow Chow': 'https://www.akc.org/dog-breeds/chow-chow/',
              'Dachshund': 'https://www.akc.org/dog-breeds/dachshund/',
              'Doberman Pinscher': 'https://www.akc.org/dog-breeds/doberman-pinscher/',
              'English Bulldog': 'https://www.akc.org/dog-breeds/english-bulldog/',
              'French Bulldog': 'https://www.akc.org/dog-breeds/french-bulldog/',
              'German Shepherd Dog': 'https://www.akc.org/dog-breeds/german-shepherd-dog/',
              'Great Dane': 'https://www.akc.org/dog-breeds/great-dane/',
              'Greyhound': 'https://www.akc.org/dog-breeds/greyhound/',
              'Havanese': 'https://www.akc.org/dog-breeds/havanese/',
              'Irish Wolfhound': 'https://www.akc.org/dog-breeds/irish-wolfhound/',
              'Jack Russell Terrier': 'https://www.therealjackrussell.com',
              'Komondor': 'https://www.akc.org/dog-breeds/komondor/',
              'Labrador Retriever': 'https://www.akc.org/dog-breeds/labrador-retriever/',
              'Miniature Dachshund': 'https://www.akc.org/dog-breeds/dachshund/',
              'Old English Sheepdog': 'https://www.akc.org/dog-breeds/old-english-sheepdog/',
              'Pit Bull Terrier': 'https://www.ukcdogs.com/american-pit-bull-terrier',
              'Pug': 'https://www.akc.org/dog-breeds/pug/',
              'Rhodesian Ridgeback': 'https://www.akc.org/dog-breeds/rhodesian-ridgeback/',
              'Rottweiler': 'https://www.akc.org/dog-breeds/rottweiler/',
              'Shar-Pei': 'https://www.akc.org/dog-breeds/chinese-shar-pei/',
              'Tibetan Mastiff': 'https://www.akc.org/dog-breeds/tibetan-mastiff/',
              'Wirehaired Dachshund': 'https://www.akc.org/dog-breeds/dachshund/',
              'Yellow Labrador Retriever': 'https://www.akc.org/dog-breeds/labrador-retriever/'}
